import './globals.css'

import { Poppins } from 'next/font/google'
import { AuthContext } from '@/app/contexts/AuthContext'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata = {
  title: 'Yale A. / Personal Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <head>
        <meta
          name="google-site-verification"
          content="-lB_lgI6pyZwILI4a10IdvgWEhkUNQ3gymxTd1sfKBY"
        />
      </head>
      <body>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  )
}
